# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=4
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=4
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=4

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit tagfield/tests
